name: slugrunner
home: https://github.com/deis/slugrunner
version: <Will be populated by the ci before publishing the chart>
description: Buildpack application runner for Deis Workflow.
maintainers:
  - name: Deis Team
    email: engineering@deis.com
